# -*- coding: utf-8 -*-
"""day1_python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m1WMOqyl-PDLeNmLMmQVPLgZqR4Npzvl
"""

import os

def clear_screen():
    # Clear the console screen
    os.system('cls' if os.name == 'nt' else 'clear')

def display_welcome_screen():
    clear_screen()
    print("==========================================")
    print("  Welcome to the Student Information App  ")
    print("==========================================")
    print("\nThis application allows you to store and")
    print("display information for one student.\n")

def display_menu():
    print("\n--- Menu ---")
    print("1. Enter Student Information")
    print("2. Display Student Information")
    print("3. Exit")
    print("------------")

def get_student_info():
    print("\n--- Enter Student Information ---")
    student_data['full_name'] = input("Full Name: ")

    while True:
        try:
            age_input = input("Age: ")
            student_data['age'] = int(age_input)
            if student_data['age'] <= 0:
                print("Age must be a positive number. Please try again.")
            else:
                break
        except ValueError:
            print("Invalid input. Please enter a valid number for age.")

    student_data['course'] = input("Course: ")
    student_data['favourite_programming_language'] = input("Favourite Programming Language: ")
    print("\nStudent information updated successfully!")
    input("Press Enter to continue...")

def display_student_info():
    print("\n--- Student Information ---")
    if student_data['full_name']:
        print(f"Full Name: {student_data['full_name']}")
        print(f"Age: {student_data['age']}")
        print(f"Course: {student_data['course']}")
        print(f"Favourite Programming Language: {student_data['favourite_programming_language']}")
    else:
        print("No student information entered yet.")
    input("Press Enter to continue...")


# Main application logic
student_data = {
    'full_name': '',
    'age': 0,
    'course': '',
    'favourite_programming_language': ''
}

def main():
    display_welcome_screen()

    running = True
    while running:
        clear_screen()
        display_welcome_screen()
        display_menu()

        choice = input("Enter your choice (1-3): ")

        if choice == '1':
            get_student_info()
        elif choice == '2':
            display_student_info()
        elif choice == '3':
            running = False
            print("\nExiting the application. Goodbye!")
        else:
            print("\nInvalid choice. Please enter a number between 1 and 3.")
            input("Press Enter to continue...")

if __name__ == "__main__":
    main()